create_clock -name clk -period 20 -waveform {0 10} [get_ports "clk"]
set_clock_transition -rise 0.1 [get_clocks "clk"]
set_clock_transition -fall 0.1 [get_clocks "clk"]
set_clock_uncertainty 0.01 [get_ports "clk"]
set_input_delay -max 1.0 [get_ports "rst"] -clock [get_clocks "clk"]
set_input_delay -max 1.0 [get_ports "start"] -clock [get_clocks "clk"]
set_input_delay -max 1.0 [get_ports "test_img"] -clock [get_clocks "clk"]
set_output_delay -max 1.0 [get_ports "done"] -clock [get_clocks "clk"]
set_output_delay -max 1.0 [get_ports "predicted_val"] -clock [get_clocks "clk"]

